version: '3.7'

networks:
  medisync-net:

services:
  orderer.medisync.com:
    container_name: orderer.medisync.com
    image: hyperledger/fabric-orderer:2.5.13
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./organizations/ordererOrganizations/medisync.com/orderers/orderer.medisync.com/msp:/var/hyperledger/orderer/msp
      - ./organizations/ordererOrganizations/medisync.com/orderers/orderer.medisync.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    networks:
      - medisync-net

# --- ORG 1 (PRODUSEN) PEERS ---
  peer0.org1.medisync.com:
    container_name: peer0.org1.medisync.com
    image: hyperledger/fabric-peer:2.5.13
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=medisync-project_medisync-net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ID=peer0.org1.medisync.com
      - CORE_PEER_ADDRESS=peer0.org1.medisync.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.medisync.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.medisync.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.medisync.com:7051
      - CORE_PEER_LOCALMSPID=ProdusenMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/org1.medisync.com/peers/peer0.org1.medisync.com/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/org1.medisync.com/peers/peer0.org1.medisync.com/tls:/etc/hyperledger/fabric/tls
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - medisync-net

  peer1.org1.medisync.com: # <-- SERVICE BARU UNTUK PEER 1
    container_name: peer1.org1.medisync.com
    image: hyperledger/fabric-peer:2.5.13
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=medisync-project_medisync-net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ID=peer1.org1.medisync.com
      - CORE_PEER_ADDRESS=peer1.org1.medisync.com:8051 # Port baru
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051 # Port baru
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.medisync.com:8052 # Port baru
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052 # Port baru
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.medisync.com:7051 # Arahkan gossip ke peer0
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.medisync.com:8051 # Gunakan port sendiri
      - CORE_PEER_LOCALMSPID=ProdusenMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/org1.medisync.com/peers/peer1.org1.medisync.com/msp:/etc/hyperledger/fabric/msp # Path sertifikat untuk peer1
      - ./organizations/peerOrganizations/org1.medisync.com/peers/peer1.org1.medisync.com/tls:/etc/hyperledger/fabric/tls # Path sertifikat untuk peer1
    command: peer node start
    ports:
      - 8051:8051 # Mapping port baru
    networks:
      - medisync-net

# --- ORG 2 (PBF) PEERS ---
  peer0.org2.medisync.com:
    container_name: peer0.org2.medisync.com
    image: hyperledger/fabric-peer:2.5.13
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=medisync-project_medisync-net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ID=peer0.org2.medisync.com
      - CORE_PEER_ADDRESS=peer0.org2.medisync.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.medisync.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.medisync.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.medisync.com:9051
      - CORE_PEER_LOCALMSPID=PBFMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/org2.medisync.com/peers/peer0.org2.medisync.com/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/org2.medisync.com/peers/peer0.org2.medisync.com/tls:/etc/hyperledger/fabric/tls
    command: peer node start
    ports:
      - 9051:9051
    networks:
      - medisync-net

  peer1.org2.medisync.com: # <-- SERVICE BARU UNTUK PEER 1
    container_name: peer1.org2.medisync.com
    image: hyperledger/fabric-peer:2.5.13
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=medisync-project_medisync-net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ID=peer1.org2.medisync.com
      - CORE_PEER_ADDRESS=peer1.org2.medisync.com:10051 # Port baru
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051 # Port baru
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.medisync.com:10052 # Port baru
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052 # Port baru
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.medisync.com:9051 # Arahkan gossip ke peer0
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.medisync.com:10051 # Gunakan port sendiri
      - CORE_PEER_LOCALMSPID=PBFMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/org2.medisync.com/peers/peer1.org2.medisync.com/msp:/etc/hyperledger/fabric/msp # Path sertifikat untuk peer1
      - ./organizations/peerOrganizations/org2.medisync.com/peers/peer1.org2.medisync.com/tls:/etc/hyperledger/fabric/tls # Path sertifikat untuk peer1
    command: peer node start
    ports:
      - 10051:10051 # Mapping port baru
    networks:
      - medisync-net

# --- ORG 3 (APOTEK) PEERS ---
  peer0.org3.medisync.com:
    container_name: peer0.org3.medisync.com
    image: hyperledger/fabric-peer:2.5.13
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=medisync-project_medisync-net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ID=peer0.org3.medisync.com
      - CORE_PEER_ADDRESS=peer0.org3.medisync.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.medisync.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.medisync.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.medisync.com:11051
      - CORE_PEER_LOCALMSPID=ApotekMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/org3.medisync.com/peers/peer0.org3.medisync.com/msp:/etc/hyperledger/fabric/msp
      - ./organizations/peerOrganizations/org3.medisync.com/peers/peer0.org3.medisync.com/tls:/etc/hyperledger/fabric/tls
    command: peer node start
    ports:
      - 11051:11051
    networks:
      - medisync-net

  peer1.org3.medisync.com: # <-- SERVICE BARU UNTUK PEER 1
    container_name: peer1.org3.medisync.com
    image: hyperledger/fabric-peer:2.5.13
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=medisync-project_medisync-net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ID=peer1.org3.medisync.com
      - CORE_PEER_ADDRESS=peer1.org3.medisync.com:12051 # Port baru
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051 # Port baru
      - CORE_PEER_CHAINCODEADDRESS=peer1.org3.medisync.com:12052 # Port baru
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052 # Port baru
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.medisync.com:11051 # Arahkan gossip ke peer0
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.medisync.com:12051 # Gunakan port sendiri
      - CORE_PEER_LOCALMSPID=ApotekMSP
    volumes:
      - /var/run/:/host/var/run/
      - ./organizations/peerOrganizations/org3.medisync.com/peers/peer1.org3.medisync.com/msp:/etc/hyperledger/fabric/msp # Path sertifikat untuk peer1
      - ./organizations/peerOrganizations/org3.medisync.com/peers/peer1.org3.medisync.com/tls:/etc/hyperledger/fabric/tls # Path sertifikat untuk peer1
    command: peer node start
    ports:
      - 12051:12051 # Mapping port baru
    networks:
      - medisync-net
      
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5.13
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.medisync.com:7051
      - CORE_PEER_LOCALMSPID=ProdusenMSP
      - CORE_PEER_TLS_ENABLED=true
      # --- TAMBAHKAN BARIS DI BAWAH INI ---
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.medisync.com/peers/peer0.org1.medisync.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.medisync.com/users/Admin@org1.medisync.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./chaincode:/opt/gopath/src/github.com/chaincode
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/channel-artifacts
    networks:
        - medisync-net